
service:
  name: call-of-the-brave

  # Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  secrets: ${file(secrets.json)}
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STRIPE_SECRET_KEY: ${self:custom.secrets.stripeSecretKey}
    STRIPE_SECRET_KEY_TEST: ${self:custom.secrets.stripeSecretKeyTest}
    MAILCHIMP_API_KEY: ${self:custom.secrets.mailchimpAPIKey}
    MAILCHIMP_LIST_ID: ${self:custom.secrets.mailchimpListId}
    MAILCHIMP_DATA_CENTRE: ${self:custom.secrets.mailchimpDataCentre}

iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  addMailSubscriber:
    handler: functions/addMailSubscriber.handler
    events:
      - http:
          path: mail
          method: post
          cors: false
  checkDiscountCode:
    handler: functions/checkDiscountCode.handler
    events:
      - http:
          path: code
          method: post
          cors: false
  createCharge:
    handler: functions/createCharge.handler
    events:
      - http:
          path: charge
          method: post
          cors: true
  createProduct:
    handler: functions/createProduct.handler
    events:
      - http:
          path: product
          method: post
          cors: false
  sendOrderEmail:
    handler: functions/sendOrderEmail.handler
    events:
      - http:
          path: email
          method: post
          cors: false
  sendMessageEmail:
    handler: functions/sendMessageEmail.handler
    events:
      - http:
          path: message
          method: post
          cors: false
  createSku:
    handler: functions/createSku.handler
    events:
      - http:
          path: sku
          method: post
          cors: false
  deleteSku:
    handler: functions/deleteSku.handler
    events:
      - http:
          path: sku
          method: delete
          cors: false
  create:
    handler: functions/createNote.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: functions/getNote.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: functions/listNote.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: functions/updateNote.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: functions/deleteNote.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
